const quotes = [
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "In the end, we will remember not the words of our enemies, but the silence of our friends. - Martin Luther King Jr.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "You miss 100% of the shots you don’t take. - Wayne Gretzky",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Act as if what you do makes a difference. It does. - William James",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "The best way to predict the future is to invent it. - Alan Kay",
    "Your time is limited, so don’t waste it living someone else’s life. - Steve Jobs",
    "You must be the change you wish to see in the world. - Mahatma Gandhi",
    "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
    "The journey of a thousand miles begins with one step. - Lao Tzu",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    "Don't cry because it's over, smile because it happened. - Dr. Seuss",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
    "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "Our greatest glory is not in never falling, but in rising every time we fall. - Confucius",
    "The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke",
    "Happiness is not something ready-made. It comes from your own actions. - Dalai Lama",
    "The purpose of our lives is to be happy. - Dalai Lama",
    "You have within you right now, everything you need to deal with whatever the world can throw at you. - Brian Tracy",
    "The mind is everything. What you think you become. - Buddha",
    "To love and be loved is to feel the sun from both sides. - David Viscott",
    "It is never too late to be what you might have been. - George Eliot",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "Be the change that you wish to see in the world. - Mahatma Gandhi",
    "The only true wisdom is in knowing you know nothing. - Socrates",
    "Not all those who wander are lost. - J.R.R. Tolkien",
    "Life is really simple, but we insist on making it complicated. - Confucius",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
    "The best revenge is massive success. - Frank Sinatra",
    "The most common way people give up their power is by thinking they don’t have any. - Alice Walker",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "If you can dream it, you can do it. - Walt Disney",
    "Life is what happens to us while we are making other plans. - Allen Saunders",
    "You become what you believe. - Oprah Winfrey",
    "The best way to predict your future is to create it. - Peter Drucker",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "Tell me and I forget. Teach me and I remember. Involve me and I learn. - Benjamin Franklin",
    "It is our choices that show what we truly are, far more than our abilities. - J.K. Rowling",
    "The only impossible journey is the one you never begin. - Tony Robbins",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "Your time is limited, so don’t waste it living someone else’s life. - Steve Jobs",
    "Whether you think you can or you think you can’t, you’re right. - Henry Ford",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Do not wait; the time will never be ‘just right.’ Start where you stand, and work with whatever tools you may have at your command. - Napoleon Hill",
    "The secret of getting ahead is getting started. - Mark Twain",
    "The best way out is always through. - Robert Frost",
    "Happiness is not by chance, but by choice. - Jim Rohn",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "To handle yourself, use your head; to handle others, use your heart. - Eleanor Roosevelt",
    "You will face many defeats in life, but never let yourself be defeated. - Maya Angelou",
    "Courage is grace under pressure. - Ernest Hemingway",
    "Do not wait to strike till the iron is hot; but make it hot by striking. - William Butler Yeats",
    "He who has a why to live can bear almost any how. - Friedrich Nietzsche",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
    "Don't judge each day by the harvest you reap but by the seeds that you plant. - Robert Louis Stevenson",
    "We must let go of the life we have planned, so as to accept the one that is waiting for us. - Joseph Campbell",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "The best preparation for tomorrow is doing your best today. - H. Jackson Brown Jr.",
    "You miss 100% of the shots you don’t take. - Wayne Gretzky",
    "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
    "To succeed in life, you need two things: ignorance and confidence. - Mark Twain",
    "Our lives begin to end the day we become silent about things that matter. - Martin Luther King Jr.",
    "We know what we are, but know not what we may be. - William Shakespeare",
    "The best way to predict the future is to invent it. - Alan Kay",
    "Don't cry because it's over, smile because it happened. - Dr. Seuss",
    "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
    "The purpose of our lives is to be happy. - Dalai Lama",
    "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
    "Act as if what you do makes a difference. It does. - William James",
    "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
    "Dream big and dare to fail. - Norman Vaughan",
    "You have within you right now, everything you need to deal with whatever the world can throw at you. - Brian Tracy",
    "The mind is everything. What you think you become. - Buddha",
    "To love and be loved is to feel the sun from both sides. - David Viscott",
    "It is never too late to be what you might have been. - George Eliot",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
    "The only true wisdom is in knowing you know nothing. - Socrates",
    "Life is really simple, but we insist on making it complicated. - Confucius",
    "The most common way people give up their power is by thinking they don’t have any. - Alice Walker"
];

const newQuoteButton = document.getElementById('newQuote');
const quoteBox = document.getElementById('quote');
const NightModeButton = document.getElementById('NightMode');
const body = document.body;

newQuoteButton.addEventListener('click', generateQuote);
NightModeButton.addEventListener('click', toggleNightMode);

function generateQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    quoteBox.innerText = quotes[randomIndex];
}

function toggleNightMode() {
    body.classList.toggle('night-mode');
}
